const countryMap = {
  "CN": "中国 🇨🇳", "China": "中国 🇨🇳",
  "AU": "澳大利亚 🇦🇺", "Australia": "澳大利亚 🇦🇺",
  "MY": "马来西亚 🇲🇾", "Malaysia": "马来西亚 🇲🇾",
  "SG": "新加坡 🇸🇬", "Singapore": "新加坡 🇸🇬",
  "DE": "德国 🇩🇪", "Germany": "德国 🇩🇪",
  "AT": "奥地利 🇦🇹", "Austria": "奥地利 🇦🇹",
  "BE": "比利时 🇧🇪", "Belgium": "比利时 🇧🇪",
  "BG": "保加利亚 🇧🇬", "Bulgaria": "保加利亚 🇧🇬",
  "HR": "克罗地亚 🇭🇷", "Croatia": "克罗地亚 🇭🇷",
  "CY": "塞浦路斯 🇨🇾", "Cyprus": "塞浦路斯 🇨🇾",
  "CZ": "捷克 🇨🇿", "Czech Republic": "捷克 🇨🇿", "Czechia": "捷克 🇨🇿",
  "DK": "丹麦 🇩🇰", "Denmark": "丹麦 🇩🇰",
  "EE": "爱沙尼亚 🇪🇪", "Estonia": "爱沙尼亚 🇪🇪",
  "FI": "芬兰 🇫🇮", "Finland": "芬兰 🇫🇮",
  "FR": "法国 🇫🇷", "France": "法国 🇫🇷",
  "GR": "希腊 🇬🇷", "Greece": "希腊 🇬🇷",
  "HU": "匈牙利 🇭🇺", "Hungary": "匈牙利 🇭🇺",
  "IE": "爱尔兰 🇮🇪", "Ireland": "爱尔兰 🇮🇪",
  "IT": "意大利 🇮🇹", "Italy": "意大利 🇮🇹",
  "LV": "拉脱维亚 🇱🇻", "Latvia": "拉脱维亚 🇱🇻",
  "LT": "立陶宛 🇱🇹", "Lithuania": "立陶宛 🇱🇹",
  "LU": "卢森堡 🇱🇺", "Luxembourg": "卢森堡 🇱🇺",
  "MT": "马耳他 🇲🇹", "Malta": "马耳他 🇲🇹",
  "NL": "荷兰 🇳🇱", "Netherlands": "荷兰 🇳🇱",
  "PL": "波兰 🇵🇱", "Poland": "波兰 🇵🇱",
  "PT": "葡萄牙 🇵🇹", "Portugal": "葡萄牙 🇵🇹",
  "RO": "罗马尼亚 🇷🇴", "Romania": "罗马尼亚 🇷🇴",
  "SK": "斯洛伐克 🇸🇰", "Slovakia": "斯洛伐克 🇸🇰",
  "SI": "斯洛文尼亚 🇸🇮", "Slovenia": "斯洛文尼亚 🇸🇮",
  "ES": "西班牙 🇪🇸", "Spain": "西班牙 🇪🇸",
  "SE": "瑞典 🇸🇪", "Sweden": "瑞典 🇸🇪",
  "UNKNOWN": "未知地区 🌐"
};
